name: Security Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/dependabot-core@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run Secret Scanning
        uses: github/secret-scanning-action@v1
